<?php
/**
 * @category    Mana
 * @package     Mana_Filters
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * Template for showing options for filter as a HTML list
 * @author Mana Team
 * Injected instead of standard catalog/layer/filter.phtml in Mana_Filters_Block_Filter_Attribute constructor.
 * This template is overridden by copying (template body was pasted from catalog/layer/filter.phtml
 * and modified as needed). All changes are marked with comments.
 */
/* @var $this Mana_Filters_Block_Filter_Attribute */
?>
<?php
    $filterUrls = Mage::helper('mana_filters/url');
?>
<ol class="m-filter-item-list <?php echo $this->getFilterOptions()->getIsReverse() ? 'm-reverse' : '' ?>">
<?php foreach ($this->getItems() as $_item): ?>
    <li <?php if ($_item->getMShowSelected()): ?>class="m-selected-ln-item"<?php endif; ?>>
        <?php // MANA BEGIN ?>
        <?php if ($_item->getMSelected()): ?>
            <a  class="m-selected-filter-item" onclick="filterItems('<?php echo $_item->getRemoveUrl() ?>');return false;"  href="<?php echo $_item->getRemoveUrl() ?>" title="<?php echo $this->escapeHtml($_item->getLabel()) ?>"><?php echo $this->escapeHtml($_item->getLabel()) ?></a>
        <?php else : ?>
	        <?php if ($_item->getCount() > 0): ?>
	        <a href="#" onclick="filterItems('<?php echo $filterUrls->getFilterUrl($this->urlEscape($_item->getReplaceUrl())); ?>');return false;" title="<?php echo $this->escapeHtml($_item->getLabel()) ?>"><?php echo $this->escapeHtml($_item->getLabel()) ?></a>
	        <?php else: ?>
            <span><?php echo $this->escapeHtml($_item->getLabel()) ?></span>
	        <?php endif; ?>
        <?php endif; ?>
        <?php // MANA END ?>
        <?php if ($this->shouldDisplayProductCount()): ?>
            (<?php echo $_item->getCount() ?>)
        <?php endif; ?>
    </li>
<?php endforeach ?>
</ol>
<?php echo Mage::helper('mana_core')->getNamedHtml('mana_filters/markup', 'after_items', array('block' => $this)) ?>
