<?php
/**
 * MagenMarket.com
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * Edit or modify this file with yourown risk.
 *
 * @category    Extensions
 * @package     Ma2_Manufacturers Free
 * @copyright   Copyright (c) 2013 MagenMarket. (http://www.magenmarket.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
**/
/* $Id: slider.phtml 3 2014-01-13 09:15:57Z linhnt $ */

$manu_code = Mage::getStoreConfig('manufacturers/general/attr_code');
$manufacturers = $this->getManufacturers();
$thumbW = intval(Mage::getStoreConfig('manufacturers/general/thumb_w')) > 0 ? intval(Mage::getStoreConfig('manufacturers/general/thumb_w')) : 120;
$thumbH = intval(Mage::getStoreConfig('manufacturers/general/thumb_h')) > 0 ? intval(Mage::getStoreConfig('manufacturers/general/thumb_h')) : 60;
$dimension_spec = intval(Mage::getStoreConfig('manufacturers/general/dimension_spec')) == 1;

$showLogo = true;
if ($this->getShowLogo() != null && (int)$this->getShowLogo() == 0) $showLogo = false; // default is show
$showName = true;
if ($this->getShowName() != null && (int)$this->getShowName() == 0) $showName = false; // default is show
$showProductCount = false;
if ($this->getShowProductCount() != null && (int)$this->getShowProductCount() == 1) $showProductCount = true; // default is not show

// grid
$gridColumn = 6;
if ($this->getGridCol() != null && (int)$this->getGridCol() > 0) $gridColumn = (int)$this->getGridCol();
$itemWidth = (100 / $gridColumn);

// uniq Id
$uniqId = Mage::helper('core')->uniqHash('manufacturers-slider-');


if(is_array($manufacturers) && count($manufacturers)): ?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('ma2_manufacturers/js/carousel-min.js') ?>"></script>
<div class="ma2-manufacturers block" id="<?php echo $uniqId; ?>">
  <div class="block-inner">
    <?php if ($this->getTitle()): ?>
    <h3 class="block-title">
      <span class="format-span">
        <span><?php echo $this->getTitle(); ?></span>
      </span>
    </h3>
    <?php endif; ?>
    <div class="controls">
        <a rel="prev" class="carousel-control ico-prev" href="javascript:">&#8249;</a>
        <a rel="next" class="carousel-control ico-next" href="javascript:">&#8250;</a>
    </div>
    <div class="manufacturers">
      <div class="slider">
        <div class="slider-inner">
        <?php
        foreach($manufacturers as $idx => $manufacturer){
          $link = '{{store url="catalogsearch/advanced/result" _query="' . $manu_code . '='.$manufacturer['value'].'"}}';
          $link_text = '';
          if ($showLogo) $link_text .= '<img class="manufacturer-logo" '. ($dimension_spec ? 'width="'.$thumbW.'" height="'.$thumbH.'"' : '') . 'src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . ($manufacturer['image'] != '' ? $manufacturer['image'] : 'manufacturers/noimage.jpg') . '" alt="'. $manufacturer['label'] .'" />';
          if ($showName) $link_text .= '<span class="manufacturer-name">' . $manufacturer['label'];
          $link_text .= $showProductCount ? ' (' . $manufacturer['product_count'] . ')' : '';
          $link_text .= '</span>';
          if ($idx == 0){ echo '<div class="manufacturer-slide">';}
          else if ($idx % $gridColumn == 0){ echo '</div><div class="manufacturer-slide">';}
          
          echo '<div class="manufacturer" style="width: '.$itemWidth.'%;">
                  <div class="manufacturer-inner">
                    <a href="'.Mage::helper('cms')->getPageTemplateProcessor()->filter($link).'" title="'.$this->escapeHtml($manufacturer['label']).'">'. $link_text . '</a>
                  </div>
                </div>';
          
          if ($idx == count($manufacturers) - 1) echo '</div>';
        }
        ?>
        </div>
      </div>
    </div>
    <div class="clear"></div>
  </div>
</div>
<script type="text/javascript">
//<![CDATA[
  Event.observe(window, "load", function() {
		
    var slideWidth = $('<?php echo $uniqId; ?>').down('.block-inner').getWidth();
		$$('#<?php echo $uniqId; ?> .slider').each(function(element){
			element.setStyle({
				width	:	slideWidth + 'px'
			});
		});
    
    $$('#<?php echo $uniqId; ?> .manufacturer').each(function(element){
			element.setStyle({
				width	:	(slideWidth * <?php echo $itemWidth ?> / 100) + 'px'
			});
		});
    
    new Carousel(
      $('<?php echo $uniqId; ?>').down('.slider'), 
      $('<?php echo $uniqId; ?>').select('.manufacturer-slide'),
      $('<?php echo $uniqId; ?>').select('.controls a'), 
      { 
        duration:		0.4,
        auto: 			false,
        frequency:		3,
        circular:		false,
        wheel:			false,
        visibleSlides:	1,
        effect:			"scroll",
        transition: 	"sinoidal"
      }
    );  
    });
	
//]]>
</script>
<?php endif; ?>
<?php 
unset($showLogo, $showName, $showProductCount);
?>
