<?php
$_output['headers'][] = '<ul class="b-tab-headers">';
foreach($this->getChildGroup('s2Tabs', 'getChildHtml') as $alias => $html){
    $title = $this->getChildData($alias, 'title');
    if (empty($title) || empty($html)) continue;
    $_output['headers'][] = '<li class="b-th-item"><a href="#tab-'. $alias .'" title="" onclick="return false;" >'. $title .'</a></li>';
    $_output['html'][] = '<div id="tab-'. $alias.'" class="b-tab-item">'. $html .'</div>';
};
$_output['headers'][] = '</ul>';
?>
<div class="b-tabs">
    <?php echo join('', $_output['headers']) ?>
    <?php echo join('', $_output['html']) ?>
</div>
